# Generated by Django 5.2.6 on 2025-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
